### PR TITLE
Goodbye

### PR DESCRIPTION
**Pull request by espenhogbakk**
This is definitely my saddest commit ever.

### CODE REVIEW

**Comment by sindrenm** [comment]
LLAP.

**Comment by jgorset** [comment]
Also definitely the saddest pull request ever.

**Comment by jgorset** [comment]
Dawson cry

**Comment by espenhogbakk** [comment]
http://i1.kym-cdn.com/entries/icons/original/000/003/398/2013_6beb.jpeg

**Comment by espenhogbakk** [comment]
Sad panda

**Comment by zenangst** [comment]
dkg5bgb

**Comment by 3lvis** [comment]
group-cry

**Pull request merged**
