### PR TITLE
Master

### PR DESCRIPTION
**Pull request by usmany**

### CODE REVIEW

**Comment by usmany** [comment]
Hi from Venezuela!

**Comment by mathiasbno** [comment]
Hey @usmany, thanks for getting in touch in this original and wonderful way. After reading the comments on Airbnb you guys sounds like a wonderful couple and makes us want to come visit. 

But there are some issues. We unfortunately don't have time to take in interns at this point, nether remote or on site. Also there is a considerable time difference between Venezuela and Norway. We would also like to see some code. A good way is to contribute to a open source projects, then you will get feedback from all over the world. 

If you find the time to make some code please send it to our [Respected Hiring Manager @jgorset](mailto:johannes@hyper.no).

**Comment by usmany** [comment]
Hi Mathias!

Thanks for your kind and quick response.
I do have some JavaScript/Bash/ActionScript (do you remember that?) code
and some examples of very basic solutions to problems that I have resolve
in very brutal ways. I will send them to Johannes for sure.

Tusen takk!
I will work hard to reach the level of proficiency and professionalism
required to work for you.

PS1.: I didn't know to to push and pull request until yesterday ;)

PS2.: You all are more than welcome to come. We just love to host people.

Many

**Comment by sindrenm** [comment]
> that I have resolve in very brutal ways.

Now this might be interresting! :smiley:

**Pull request closed without merging**
